# Generated by Django 4.1.1 on 2022-09-11 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите имя', max_length=40, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Введите фамилию', max_length=40, verbose_name='Фамилия')),
                ('last_last_name', models.CharField(help_text='Введите отчество', max_length=40, verbose_name='Отчество')),
                ('number', models.CharField(help_text='Укажите номер телефона', max_length=100, verbose_name='Номер телефона')),
                ('address', models.CharField(help_text='Укажите адрес', max_length=100, verbose_name='Адрес')),
                ('advert_status', models.CharField(help_text='Укажите статус рекламы', max_length=100, verbose_name='Статус рекламы')),
            ],
            options={
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_service', models.CharField(help_text='Выберите статус договора', max_length=30, verbose_name='Тип услуги')),
                ('service_description', models.TextField(help_text='Введите описание услуги', max_length=1500, verbose_name='Описание услуги')),
                ('short_service_description', models.TextField(help_text='Введите короткое описание услуги', max_length=150, null=True, verbose_name='Короткое описание услуги')),
            ],
            options={
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите имя', max_length=40, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Введите фамилию', max_length=40, verbose_name='Фамилия')),
                ('last_last_name', models.CharField(help_text='Введите отчество', max_length=40, verbose_name='Отчество')),
                ('address', models.CharField(help_text='Укажите адрес', max_length=100, verbose_name='Адрес')),
                ('number', models.CharField(help_text='Укажите номер телефона', max_length=100, verbose_name='Номер телефона')),
                ('specialization', models.CharField(help_text='Введите специальность', max_length=100, verbose_name='Специальность')),
                ('type_staff', models.CharField(help_text='Введите тип персонала', max_length=20, null=True, verbose_name='Тип персонала')),
            ],
            options={
                'verbose_name_plural': 'Персонал',
            },
        ),
        migrations.CreateModel(
            name='BioStaff',
            fields=[
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user_site_part.staff', verbose_name='Персонал')),
                ('bio', models.TextField(help_text='Введите описание персонала', max_length=200, verbose_name='Описание персонала')),
                ('root_to_image', models.CharField(help_text='Введите адрес к фото персонала', max_length=150, null=True, verbose_name='Адрес до фото персонала')),
            ],
            options={
                'verbose_name_plural': 'Биография персонала',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Выберите дату приема', verbose_name='Дата визита')),
                ('time_start_visit', models.TimeField(help_text='Выберите время начала приема', verbose_name='Время начала визита')),
                ('time_end_visit', models.TimeField(help_text='Выберите время окончания приема', verbose_name='Время окончания визита')),
                ('summ_visit', models.IntegerField(help_text='Введите сумму посещения', verbose_name='Сумма посещения')),
                ('status', models.CharField(help_text='Введиет статус приема', max_length=20, null=True, verbose_name='Статус приема')),
                ('service', models.ForeignKey(help_text='Выберите услуги', on_delete=django.db.models.deletion.PROTECT, to='user_site_part.service', verbose_name='Услуга')),
                ('who_accept', models.ForeignKey(help_text='Выберите кто обслуживал', null=True, on_delete=django.db.models.deletion.CASCADE, to='user_site_part.staff', verbose_name='Обслуживал:')),
                ('who_visit', models.ForeignKey(help_text='Введите ФИО клиента', null=True, on_delete=django.db.models.deletion.PROTECT, to='user_site_part.client', verbose_name='ФИО клиент')),
            ],
            options={
                'verbose_name_plural': 'Посещения',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='staff_list',
            field=models.ManyToManyField(help_text='Выберите специалиста', to='user_site_part.staff', verbose_name='Cпециалисты'),
        ),
        migrations.CreateModel(
            name='PriceVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(help_text='Установить цену', verbose_name='Цена')),
                ('service', models.ForeignKey(help_text='Выберите услугу', on_delete=django.db.models.deletion.CASCADE, to='user_site_part.service', verbose_name='Услуга')),
                ('staff', models.ForeignKey(help_text='Выберите персонал', on_delete=django.db.models.deletion.CASCADE, to='user_site_part.staff', verbose_name='Персонал')),
            ],
            options={
                'verbose_name_plural': 'Цены',
            },
        ),
        migrations.CreateModel(
            name='PayrollPreparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summ_payroll', models.IntegerField(help_text='Введите сумму', verbose_name='Заработная плата')),
                ('month', models.DateField(help_text='Введите месяц', verbose_name='Месяц')),
                ('status', models.CharField(help_text='Введите статус выдачи', max_length=20, verbose_name='Статус выдачи')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_site_part.staff')),
            ],
            options={
                'verbose_name_plural': 'Зарплаты',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contract', models.CharField(help_text='Введите тип контракта', max_length=20, verbose_name='Тип договора')),
                ('description_contract', models.TextField(help_text='Введите описание контракта', max_length=100, verbose_name='Описание контракта')),
                ('client_side', models.ForeignKey(help_text='Выберите клиента', null=True, on_delete=django.db.models.deletion.CASCADE, to='user_site_part.client')),
                ('who_accept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_site_part.staff')),
            ],
            options={
                'verbose_name_plural': 'Контракты',
            },
        ),
    ]
